# Generated by Django 2.1.7 on 2020-05-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuralNetwork', '0002_network_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='sharable',
            field=models.BooleanField(default=False),
        ),
    ]
