# Generated by Django 2.1.7 on 2020-05-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20200420_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='pic',
            field=models.ImageField(default='default.jpg', upload_to='usr_img'),
        ),
    ]
