# Generated by Django 2.1.7 on 2020-05-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comments_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='pic',
            field=models.TextField(max_length=140),
        ),
    ]
