# Generated by Django 2.1.7 on 2020-05-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20200514_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='pic',
            field=models.TextField(default='default.jpg', max_length=140),
        ),
    ]
